filebeat.modules:
    - module: nginx
      access:
          enabled: true
          var.paths:
              - /var/log/nginx/access.log
      error:
          enabled: true
          var.paths:
              - /var/log/nginx/error.log

output.elasticsearch:
    hosts: ["http://es:9200"]

setup.ilm.enabled: true

logging.level: info
